using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace TextorcistAutosplitter
{
    internal class TextTypingEngine
    {
        private readonly MainWindowViewModel _viewModel;
        private string _textToType;
        private string _textTyped;

        public bool IsMoving { get; set; }
        public string TextToType => _textToType;
        public string TextTyped => _textTyped;

        public event Action? TypedAmen;

        public TextTypingEngine(MainWindowViewModel viewModel)
        {
            _viewModel = viewModel;
            _textToType = string.Empty;
            _textTyped = string.Empty;
        }

        public void SetText(string boss)
        {
            _textToType = new Regex("[^A-Z]").Replace(TEXTS[boss.ToLower()].ToUpper(), "");
        }

        public void OnLetterPressed(char c)
        {
            if (IsMoving && _viewModel.Keys.Contains(c)) return;
            _textTyped += c;
            if (_textTyped.EndsWith("AMEN"))
            {
                TypedAmen?.Invoke();
                _textTyped = string.Empty;
            }
        }

        public static Dictionary<string, string> TEXTS = new Dictionary<string, string>()
        {
            { "caesar", "SHUT UP;REDEEM YOURSELF AT ONCE;WRETCHED SOUL CEASE YOUR EXISTENCE,OF CRIME AMEN" },
            { "magda", "SAINT MICHAEL THE ARCHANGEL;DEFEND US IN OUR BATTLE AGAINST THE,DARKNESS;AGAINST POWERS AND THE SPIRITS OF,EVIL IN THE HIGH PLACES;FOR THE POWERS GRANTED TO ME I,BANISH YOU MONSTER FROM THIS,VESSEL AMEN" },
            { "matthew", "WITNESS THE CROSS OF THE LORD FLEE,AWAY YE HOSTILES;MAY THY MERCY O LORD REST UPON US,FOR WE HAVE HOPE;THE LION OF THE TRIBE OF JUDAH THE,ROOT OF DAVID HATH CONQUERED;WE CAST YOU OUT EVERY UNCLEAN,SPIRIT EVERY SATANIC POWER AND,ONSLAUGHT;CURSED DRAGON WE ADJURE YOU MAY THE,LORD BE WITH YOU AND WITH THY,SPIRIT AMEN" },
            { "enoch varg", "BEHOLD THE ANCIENT ENEMY AND,MURDERER STRONGLY RAISES HIS,HEAD;FIGHT THE LORD BATTLES WITH THE,UNDEFEATED ARMY OF THE ANGELS;AS ONCE THOU DIDST FIGHT THE FIRST,APOSTATE AND HE PREVAILED NOT;WHERE THE SEE OF PETER HAS BEEN,SETTLED FOR THE LIGHT OF THE,GENTILES;WHEN THE GREAT BEHEMOTH WAS CAST,OUT THE SERPENT CALLED THE DEVIL,SEDUCED THE WORLD;PRAY THE GOD OF PEACE TO CRUSH,SATAN MAY HE NO MORE BE ABLE TO,HARM INNOCENTS AMEN" },
            { "mother superior", "IN NOMINE DEI PATRIS OMNIPOTENTIS,EXORCIZO TE;ET IN NOMINE JESU CHRISTI ET IN,VIRTUTE SPIRITUS SANCTI;UT DESCADAS AD HOC PLASMATE DEI,QUOD DOMINUS NOSTER;AD TEMPLUM SANCTUM SUUM VOCARE EST,UT FIAT TEMPLUM DEI VIVI;CRUX SACRA SIT MIHI LUX NUNQUAM,DRACO SIT MIHI DUX VADE RETRO,SATANA;EGO TE LINIO OLEO SALUTIS IN,CHRISTO JESU DOMINO NOSTRO UT,HABEAS VITAM AETERNAM AMEN" },
            { "master", "THE SACRED SIGN OF THE CROSS THE,GLORIOUS MOTHER OF GOD COMMANDS,YOU;REGNA TERRAE CANTATA DEO PSALLITE,CERNUNNOS REGNA TERRAE CANTATA,DEA PSALLITE ARADIA;CAELI DEUS HUMILITER MAJESTATI,GLORIA TUAE SUPPLICAMUS UT AB,OMNI INFERNALIUM SPIRITUUM,POTESTATE;AB INSIDIIS DIABOLI LIBERA NOS,DOMINATES UT COVEN TUAM SECURA,TIBI LIBERTATE SERVIRE FACIAS TE,ROGAMUS AUDI NOS;TERRIBILIS DEUS SANCTUARIO SUO,CERNUNNOS IPSE TRUDERIT VIRTUTEM,PLEBI SUAE ARADIA IPSE,FORTITUDINEM PLEBI SUAE;MAY HIS SOUL THROUGH THE MERCY OF,GOD REST IN PEACE AMEN" },
            { "furius", "BEGONE SATAN MASTER OF ALL DECEIT,AND ENEMY OF HUMAN SALVATION;PRINCEPS GLORIOSISSIME CAELESTIS,MILITIAE SANCTE MICHAEL,ARCHANGELE DEFENDE NOS;VENI IN AUXILIUM HOMINUM QUOS DEUS,CREAVIT INEXTERMINABILES ET AD,IMAGINEM SUAE FECIT;ADESTO ITAQUE DUX INVICTISSIME,POPULO DEI CONTRA IRRUMPENTES,SPIRITUALES NEQUITIAS ET FAC,VICTORIAM;UBI SEDES PETRI ET CATHEDRA,VERITATIS AD LUCEM GENTIUM,CONSTITUTA EST IBI THRONUM,POSUERUNT ABOMINATIONIS;SED PROJECTUS EST DRACO ILLE MAGNUS,SERPENS ANTIQUUS QUI VOCATUR,SATANAS QUI SEDUCIT UNIVERSUM,ORBEM AMEN" },
            { "cardinal", "IN THE NAME AND BY THE POWER OF OUR,LORD JESUS CHRIST WE CHANT;MAY YOU BE SNATCHED AWAY FROM THIS,FIEND AND REDEEMED BY THE DIVINE,LAMB;TRANSFIGURATUS IN ANGELUM LUCIS CUM,TOTA MALIGNORUM SPIRITUUM,CATERVA LATE CIRCUIT;ECCLESIAM AGNI IMMACULATI SPONSAM,FAVERRIMI HOSTES REPLEVERUNT,AMARITUDINIBUS INEBRIARUNT,ABSINTHIO;VIRUS NEQUITIAE SUAE TAMQUAM FLUMEN,IMMUNDISSIMUM DRACO MALEFICUS,TRANSFUNDIT IN HOMINES,DEPRAVATOS MENTE;UT IN EA DELEAT NOMEN DEI AD,AETERNAE GLORIAE CORONAM,DESTINATAS FURETUR MACTET AC,PERDAT ININTERITUM AMEN" },
            { "laurentius", "VADE SATANA INVENTOR ET MAGISTER,OMNIS FALLACIE HOSTIS HUMANAE,SALUTIS;DA LOCUM ECCLESIAE UNI SANCTAE QUAM,CHRISTUS IPSE ACQUISIVIT,SANGUINE SUO;HUMILIARE SUB POTENTI MANU DEI,CONTREMISCE A NOBIS SANCTO ET,TERRIBILI NOMINE JESU;QUEM INFERI TREMUNT CUI VIRTUTES,SUBJECTAE SUNT QUEM SERAPHIM,INDEFESSIS VOCIBUS LAUDANT;DICENTES SANCTUS DOMINUS DEUS,SABAOTH DOMINE EXAUDI,ORATIONEM MEAM ET CLAMOR,MEUS AD TE VENIAT;GLORIAE TUAE SUPPLICAMUS UT AB OMNI,INFERNALIUM SPIRITUM POTESTATE,LAQUEO DECEPTIONE NOS POTENTER,LIBERARE AMEN" },
            { "lilith", "EXSURGAT DEUS ET DISSIPENTUR,INIMICI EJUS ET FUGIANT QUI,ODERUNT EUM A FACIE EJUS;JUDICA DOMINE NOCENTES ME EXPUGNA,IMPUGNANTES ME CONFUNDANTUR,QUAERENTES ANIMAM MEAM;QUONIAM GRATIS ABSCONDERUNT MIHI,INTERITUM LAQUEI SUI SUPERVACUE,EXPROBAVERUNT ANIMAM MEAM;SICUT DEFICIT FUMUS DEFICIANT SICUT,FLUIT CERA A FACIE IGNIS SIC,PEREANT PECCATORES A FACIE DEI;AVERTANTUR RETRORSUM ET,CONFUNDANTUR COGITANTES MAHI,MALA FIANT TAMQUAM PALVIS ANTE,FACIEM VENTI;GLORIA PATRI ET FILIO ET SPIRITUS,SANCTO SICUT ERAT IN PRINCIPIO,ET NUNC ET SEMPER IN SAECULA,SECULORUM AMEN" },
        };
    }
}
